export default {
  // button
  BUTTON_STATE_NORMAL: 0,
  BUTTON_STATE_HIGHLIGHT: 1,
  BUTTON_STATE_PRESSED: 2,
  BUTTON_STATE_DISABLED: 3,

  BUTTON_TRANSITION_NONE: 0,
  BUTTON_TRANSITION_COLOR_TINT: 1,
  BUTTON_TRANSITION_SPRITE_SWAP: 2,
  BUTTON_TRANSITION_ANIMATION: 3,

  // mode
  HORIZONTAL: 0,
  VERTICAL: 1,
  filled: 2,

  // TOUCH
  DOWN: 0,
  UP: 1,
  DRAG: 2,
  MOVE: 3,
  ENTER: 4,
  RELEASE: 5,

  // scrollView
  UNRESTRICTED: 0,
  CLAMPED: 1

};